// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTsxD836xl6e8eNcNvkbvVQRANAAzLYwc',
    appId: '1:137708355317:web:cf7dd9be37b76d17cf4fbc',
    messagingSenderId: '137708355317',
    projectId: 'food-app-design-1d238',
    authDomain: 'food-app-design-1d238.firebaseapp.com',
    storageBucket: 'food-app-design-1d238.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_nWw3YWPk3QQ3Dg53MvPfLMEq_oWsNI',
    appId: '1:137708355317:android:9435e7b403e67b86cf4fbc',
    messagingSenderId: '137708355317',
    projectId: 'food-app-design-1d238',
    storageBucket: 'food-app-design-1d238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5Z4zT4rFfQrXes-yroszsD3ejEyf3RQ',
    appId: '1:137708355317:ios:c1ea98221f068712cf4fbc',
    messagingSenderId: '137708355317',
    projectId: 'food-app-design-1d238',
    storageBucket: 'food-app-design-1d238.firebasestorage.app',
    iosBundleId: 'com.example.foodAppDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl5Z4zT4rFfQrXes-yroszsD3ejEyf3RQ',
    appId: '1:137708355317:ios:c1ea98221f068712cf4fbc',
    messagingSenderId: '137708355317',
    projectId: 'food-app-design-1d238',
    storageBucket: 'food-app-design-1d238.firebasestorage.app',
    iosBundleId: 'com.example.foodAppDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTsxD836xl6e8eNcNvkbvVQRANAAzLYwc',
    appId: '1:137708355317:web:8fc319b3d9dd3647cf4fbc',
    messagingSenderId: '137708355317',
    projectId: 'food-app-design-1d238',
    authDomain: 'food-app-design-1d238.firebaseapp.com',
    storageBucket: 'food-app-design-1d238.firebasestorage.app',
  );
}
